# Generated by Django 4.2.7 on 2024-01-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('owner', models.TextField()),
                ('repo_url', models.TextField()),
                ('created_date', models.TextField()),
                ('updated_date', models.TextField()),
                ('description', models.TextField(null=True)),
                ('last_push_date', models.TextField()),
                ('latest_commit_date', models.TextField()),
                ('stars', models.BigIntegerField()),
                ('forks', models.BigIntegerField()),
                ('watchers', models.BigIntegerField()),
                ('languages', models.JSONField()),
                ('tags', models.JSONField()),
                ('open_prs', models.IntegerField()),
                ('open_issues', models.IntegerField()),
                ('top_contributors', models.JSONField()),
                ('status', models.CharField(max_length=20)),
                ('sdg_categories', models.JSONField(null=True)),
                ('readme', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.TextField()),
                ('favourite_projects', models.JSONField()),
            ],
        ),
    ]
