# Generated by Django 4.2.7 on 2024-01-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_user_id_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='newcomer_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
