# Generated by Django 4.2.7 on 2024-01-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_project_newcomer_friendly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
    ]
