# Generated by Django 4.2.7 on 2024-01-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_project_repo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner_avatar',
            field=models.TextField(default=''),
        ),
    ]
