# Generated by Django 4.2.7 on 2024-01-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_project_owner_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner_avatar',
            field=models.TextField(),
        ),
    ]
