# Generated by Django 4.2.7 on 2024-01-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_projects',
            field=models.JSONField(null=True),
        ),
    ]
