# Generated by Django 4.2.7 on 2024-02-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatar_url',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
