import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import Nav from "./ui/nav";
import { cn } from "@/lib/utils";
import { GlobalContextProvider } from "./context";
import { SessionProvider, getSession } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });
const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-outfit",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <body
          className={cn(
            outfit.className,
            "h-[100vh] flex flex-col overflow-auto"
          )}
        >
          {/* <SessionProvider session={session}> */}
          <GlobalContextProvider>
            <Nav />
            {children}
          </GlobalContextProvider>
          {/* </SessionProvider> */}
        </body>
      </html>
    </>
  );
}
