import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./ui/nav";
import { cn } from "@/lib/utils";
import { GlobalContextProvider } from "./context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <body
          className={cn(
            inter.className,
            "h-[100vh] flex flex-col overflow-auto"
          )}
        >
          <GlobalContextProvider>
            <Nav />
            {children}
          </GlobalContextProvider>
        </body>
      </html>
    </>
  );
}
